### ISSUE TITLE
sled-related crash

### ISSUE THREAD

**Issue by nullchinchilla** [geph-official/geph4#19]
thread 'sscale-wkr-c' panicked at 'could not acquire lock on "/home/miyuruasuka/.config/geph4-credentials/db": Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', geph4-client/src/cache.rs:61:25        note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace                                                                                                                                                          thread 'main' panicked at 'task has failed', /home/miyuruasuka/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.0.3/src/task.rs:368:45

**Comment by nullchinchilla** [comment]
Fixed in ed26c69
